name: run-dockerized-tests
on: [pull_request]
jobs:
  format:
    name: Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: moonrepo/setup-rust@v1
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features --workspace

  dockerized-tests:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - name: build
        run : docker compose -f ./docker-compose.yml build
      - name: Run tests
        run : docker compose -f ./docker-compose.yml run test
